cat-home/src/main/java/com/dianping/cat/report/page/model/Payload.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.report.page.model;

import java.util.Arrays;

import org.unidal.web.mvc.ActionContext;
import org.unidal.web.mvc.ActionPayload;
import org.unidal.web.mvc.payload.annotation.FieldMeta;
import org.unidal.web.mvc.payload.annotation.PathMeta;

import com.dianping.cat.mvc.ApiPayload;
import com.dianping.cat.report.ReportPage;
import com.dianping.cat.report.service.ModelPeriod;

public class Payload extends ApiPayload implements ActionPayload<ReportPage, Action> {
	@FieldMeta("op")
	private Action m_action;

	private ReportPage m_page;

	@PathMeta("path")
	private String[] m_path;

	@Override
	public Action getAction() {
		return m_action;
	}

	public void setAction(String action) {
		m_action = Action.getByName(action, Action.XML);
	}

	public String getDomain() {
		if (m_path.length > 1) {
			return m_path[1];
		} else {
			return null;
		}
	}

	@Override
	public ReportPage getPage() {
		return m_page;
	}

	@Override
	public void setPage(String page) {
		m_page = ReportPage.getByName(page, ReportPage.MODEL);
	}

	public ModelPeriod getPeriod() {
		if (m_path.length > 2) {
			return ModelPeriod.getByName(m_path[2], ModelPeriod.CURRENT);
		} else {
			return ModelPeriod.CURRENT;
		}
	}

	public String getReport() {
		if (m_path.length > 0) {
			return m_path[0];
		} else {
			return null;
		}
	}

	public void setPath(String[] path) {
		if (path == null) {
			m_path = new String[0];
		} else {
			m_path = Arrays.copyOf(path, path.length);
		}
	}

	@Override
	public void validate(ActionContext<?> ctx) {
		if (m_action == null) {
			m_action = Action.XML;
		}
	}
}

cat-home/src/main/java/com/dianping/cat/report/page/business/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.report.page.business;

public enum Action implements org.unidal.web.mvc.Action {
	VIEW("view");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/business/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.business;

public enum Action implements org.unidal.web.mvc.Action {
	LIST("list"),

	ADD("add"),

	AddSubmit("addSubmit"),

	DELETE("delete"),

	TagConfig("tagConfig"),

	AlertRuleAdd("alertRuleAdd"),

	AlertRuleAddSubmit("alertRuleAddSubmit"),

	CustomAdd("customAdd"),

	CustomAddSubmit("customAddSubmit"),

	CustomDelete("customDelete");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/config/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.config;

public enum Action implements org.unidal.web.mvc.Action {
	PROJECT_ALL("projects"),

	PROJECT_ADD("projectAdd"),

	PROJECT_UPDATE_SUBMIT("updateSubmit"),

	PROJECT_DELETE("projectDelete"),

	TOPOLOGY_GRAPH_NODE_CONFIG_LIST("topologyGraphNodeConfigList"),

	TOPOLOGY_GRAPH_NODE_CONFIG_ADD_OR_UPDATE("topologyGraphNodeConfigAdd"),

	TOPOLOGY_GRAPH_NODE_CONFIG_ADD_OR_UPDATE_SUBMIT("topologyGraphNodeConfigAddSumbit"),

	TOPOLOGY_GRAPH_NODE_CONFIG_DELETE("topologyGraphNodeConfigDelete"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_ADD_OR_UPDATE("topologyGraphEdgeConfigAdd"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_ADD_OR_UPDATE_SUBMIT("topologyGraphEdgeConfigAddSumbit"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_DELETE("topologyGraphEdgeConfigDelete"),

	TOPOLOGY_GRAPH_EDGE_CONFIG_LIST("topologyGraphEdgeConfigList"),

	TOPO_GRAPH_FORMAT_CONFIG_UPDATE("topoGraphFormatUpdate"),

	HEARTBEAT_RULE_CONFIG_LIST("heartbeatRuleConfigList"),

	HEARTBEAT_RULE_ADD_OR_UPDATE("heartbeatRuleUpdate"),

	HEARTBEAT_RULE_ADD_OR_UPDATE_SUBMIT("heartbeatRuleSubmit"),

	HEARTBEAT_RULE_DELETE("heartbeatRulDelete"),

	ALERT_DEFAULT_RECEIVERS("alertDefaultReceivers"),

	ALERT_POLICY("alertPolicy"),

	HEARTBEAT_DISPLAY_POLICY("displayPolicy"),

	EXCEPTION("exception"),

	EXCEPTION_THRESHOLD_UPDATE("exceptionThresholdUpdate"),

	EXCEPTION_THRESHOLD_ADD("exceptionThresholdAdd"),

	EXCEPTION_THRESHOLD_UPDATE_SUBMIT("exceptionThresholdUpdateSubmit"),

	EXCEPTION_THRESHOLD_DELETE("exceptionThresholdDelete"),

	EXCEPTION_EXCLUDE_ADD("exceptionExcludeAdd"),

	EXCEPTION_EXCLUDE_UPDATE_SUBMIT("exceptionExcludeUpdateSubmit"),

	EXCEPTION_EXCLUDE_DELETE("exceptionExcludeDelete"),

	TRANSACTION_RULE("transactionRule"),

	TRANSACTION_RULE_ADD_OR_UPDATE("transactionRuleUpdate"),

	TRANSACTION_RULE_ADD_OR_UPDATE_SUBMIT("transactionRuleSubmit"),

	TRANSACTION_RULE_DELETE("transactionRuleDelete"),

	EVENT_RULE("eventRule"),

	EVENT_RULE_ADD_OR_UPDATE("eventRuleUpdate"),

	EVENT_RULE_ADD_OR_UPDATE_SUBMIT("eventRuleSubmit"),

	EVENT_RULE_DELETE("eventRuleDelete"),

	STORAGE_RULE("storageRule"),

	STORAGE_RULE_ADD_OR_UPDATE("storageRuleUpdate"),

	STORAGE_RULE_ADD_OR_UPDATE_SUBMIT("storageRuleSubmit"),

	STORAGE_RULE_DELETE("storageRuleDelete"),

	STORAGE_GROUP_CONFIG_UPDATE("storageGroupConfigUpdate"),

	DOMAIN_GROUP_CONFIGS("domainGroupConfigs"),

	DOMAIN_GROUP_CONFIG_UPDATE("domainGroupConfigUpdate"),

	DOMAIN_GROUP_CONFIG_SUBMIT("domainGroupConfigSubmit"),

	DOMAIN_GROUP_CONFIG_DELETE("domainGroupConfigDelete"),

	ROUTER_CONFIG_UPDATE("routerConfigUpdate"),

	SAMPLE_CONFIG_UPDATE("sampleConfigUpdate"),

	ALERT_SENDER_CONFIG_UPDATE("alertSenderConfigUpdate"),

	SERVER_FILTER_CONFIG_UPDATE("serverFilterConfigUpdate"),

	SERVER_CONFIG_UPDATE("serverConfigUpdate"),

	REPORT_RELOAD_CONFIG_UPDATE("reportReloadConfigUpdate"),

	ALL_REPORT_CONFIG("allReportConfig");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/login/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.login;

public enum Action implements org.unidal.web.mvc.Action {
	LOGIN("login"),

	LOGOUT("logout");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/login/LoginAction.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.login;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Retention(RUNTIME)
@Target(METHOD)
public @interface LoginAction {
	String[] includes() default {};

	String[] excludes() default {};
}

cat-home/src/main/java/com/dianping/cat/system/page/permission/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.permission;

public enum Action implements org.unidal.web.mvc.Action {
	USER("user"),

	RESOURCE("resource"),

	ERROR("error");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/plugin/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.plugin;

public enum Action implements org.unidal.web.mvc.Action {
	VIEW("view"),

	DOCFILE("doc");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/java/com/dianping/cat/system/page/project/Action.java
/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.cat.system.page.project;

public enum Action implements org.unidal.web.mvc.Action {
	DOMAINS("domains"),

	PROJECT_UPDATE("projectUpdate");

	private String m_name;

	private Action(String name) {
		m_name = name;
	}

	public static Action getByName(String name, Action defaultAction) {
		for (Action action : Action.values()) {
			if (action.getName().equals(name)) {
				return action;
			}
		}

		return defaultAction;
	}

	@Override
	public String getName() {
		return m_name;
	}
}

cat-home/src/main/webapp/jsp/system/business/add.jsp
<%@ page contentType="text/html; charset=utf-8" %>
<%@ taglib prefix="a" uri="/WEB-INF/app.tld"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="res" uri="http://www.unidal.org/webres"%>
<%@ taglib prefix="w" uri="http://www.unidal.org/web/core"%>

<jsp:useBean id="ctx" type="com.dianping.cat.system.page.business.Context" scope="request"/>
<jsp:useBean id="payload" type="com.dianping.cat.system.page.business.Payload" scope="request"/>
<jsp:useBean id="model" type="com.dianping.cat.system.page.business.Model" scope="request"/>

<a:config>
	<res:useJs value="${res.js.local['jquery.validate.min.js']}" target="head-js" />
	<res:useJs value="${res.js.local['alarm_js']}" target="head-js" />
	<res:useCss value="${res.css.local['select2.css']}" target="head-css" />
	<res:useJs value="${res.js.local['select2.min.js']}" target="head-js" />
	<res:useCss value="${res.css.local['multiple-select.css']}" target="head-css" />
	<res:useJs value="${res.js.local['jquery.multiple.select.js']}" target="head-js" />
	
		<h4 class="text-success text-center">修改业务监控规则</h4>
		<form name="addSubmit" id="form" method="post" action="">
			<table class="table table-striped table-condensed  ">
				<tr>
					<td width="20%" style="text-align:right"  class="text-success">项目名称</td>
					<td width="20%" >
						<c:if test="${not empty payload.domain}">
							<input name="" value="${payload.domain}" readonly required/>
						</c:if>
					</td>
					<td width="25%" style="text-align:right" class="text-success">BusinessKey</td>
					<td width="35%" >
						<c:if test="${not empty model.businessItemConfig.id}">
							<input name="businessItemConfig.id" id="businessItemConfig_id" value="${model.businessItemConfig.id}" readonly required/>
						</c:if>
						<c:if test="${empty  model.businessItemConfig.id}">
							<input name="businessItemConfig.id" id="businessItemConfig_id" value="${model.businessItemConfig.id}" required/>
						</c:if>
					</td>
				</tr>
				<tr>
					<td  style="text-align:right" class="text-success">显示标题</td>
					<td ><input name="businessItemConfig.title" id="businessItemConfig_title" value="${model.businessItemConfig.title}" required/></td>
					<td  style="text-align:right" class="text-success">显示顺序（数字）</td>
					<td ><input name="businessItemConfig.viewOrder" id="businessItemConfig_viewOrder" value="${model.businessItemConfig.viewOrder}" required/></td>
				</tr>
				<tr>
					<td style="text-align:right" class="text-success">是否告警</td>
					<td >
						<c:choose>
							<c:when test="${model.businessItemConfig.alarm}">
								<input type="radio" name="businessItemConfig_alarm" value="true" checked />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_alarm" value="false" />否
							</c:when>
							<c:otherwise>
						    	<input type="radio" name="businessItemConfig_alarm" value="true" />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_alarm" value="false" checked />否
							</c:otherwise>
						</c:choose>
					</td>
					<td style="text-align:right" class="text-success" >显示次数曲线</td>
					<td>
						<c:choose>
							<c:when test="${model.businessItemConfig.showCount}">
								<input type="radio" name="businessItemConfig_showCount" value="true" checked />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showCount" value="false" />否
							</c:when>
							<c:otherwise>
						    	<input type="radio" name="businessItemConfig_showCount" value="true" />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showCount" value="false" checked />否
							</c:otherwise>
						</c:choose>
					</td>
				</tr>
				<tr>
					<td style="text-align:right" class="text-success" >显示平均曲线</td>
					<td>
						<c:choose>
							<c:when test="${model.businessItemConfig.showAvg}">
								<input type="radio" name="businessItemConfig_showAvg" value="true" checked />是	&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showAvg" value="false" />否
							</c:when>
							<c:otherwise>
						    	<input type="radio" name="businessItemConfig_showAvg" value="true" />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showAvg" value="false" checked />否
							</c:otherwise>
						</c:choose>
					</td>
					<td style="text-align:right" class="text-success">显示求和曲线</td>
					<td>
						<c:choose>
							<c:when test="${model.businessItemConfig.showSum}">
								<input type="radio" name="businessItemConfig_showSum" value="true" checked />是	&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showSum" value="false" />否
							</c:when>
							<c:otherwise>
						    	<input type="radio" name="businessItemConfig_showSum" value="true" />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_showSum" value="false" checked />否
							</c:otherwise>
						</c:choose>
					</td>
				</tr>
				<tr>
				<td style="text-align:right" class="text-success">是否为敏感数据</td>
					<td colspan='3'>
						<c:choose>
							<c:when test="${model.businessItemConfig.privilege}">
								<input type="radio" name="businessItemConfig_privilege" value="true" checked />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_privilege" value="false" />否
							</c:when>
							<c:otherwise>
						    	<input type="radio" name="businessItemConfig_privilege" value="true" />是&nbsp;&nbsp;&nbsp;
								<input type="radio" name="businessItemConfig_privilege" value="false" checked />否
							</c:otherwise>
						</c:choose>
					</td>
				</tr>
				<tr>
					<td style="text-align:center" colspan='4'><input class='btn btn-primary btn-xs' id="addOrUpdateNodeSubmit" type="text" name="submit" value="提交" /></td>
				</tr>
			</table>
		</form>

	<script>
		$(document).ready(function(){
			$('#application_config').addClass('active open');
			$('#businessConfig').addClass('active');

			$(document).delegate("#addOrUpdateNodeSubmit","click",function(){
                window.location.href = "${model.pageUri}?op=addSubmit&domain=${payload.domain}"
                + "&businessItemConfig.id=" + encodeURIComponent($("#businessItemConfig_id").val())
                +  "&businessItemConfig.title=" + encodeURIComponent($("#businessItemConfig_title").val())
                +  "&businessItemConfig.viewOrder=" + $("#businessItemConfig_viewOrder").val()
                +  "&businessItemConfig.alarm=" + $('input:radio[name="businessItemConfig_alarm"]:checked').val()
                +  "&businessItemConfig.showCount=" + $('input:radio[name="businessItemConfig_showCount"]:checked').val()
                +  "&businessItemConfig.showAvg=" + $('input:radio[name="businessItemConfig_showAvg"]:checked').val()
                +  "&businessItemConfig.showSum=" + $('input:radio[name="businessItemConfig_showSum"]:checked').val()
                +  "&businessItemConfig.privilege=" + $('input:radio[name="businessItemConfig_privilege"]:checked').val()
                ;
			});
		});
	</script>
</a:config>

cat-home/src/main/webapp/jsp/system/business/tag.jsp
<%@ page contentType="text/html; charset=utf-8" %>
<%@ taglib prefix="a" uri="/WEB-INF/app.tld"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="res" uri="http://www.unidal.org/webres"%>
<%@ taglib prefix="w" uri="http://www.unidal.org/web/core"%>

<a:config>
	<res:useJs value="${res.js.local['jquery.validate.min.js']}" target="head-js" />
	<res:useJs value="${res.js.local['editor.js']}" target="head-js" />
	<script src='${model.webapp}/assets/js/editor/ace.js'></script>

			<form name="tagConfig" id="form" method="post"
				action="${model.pageUri}?op=tagConfig">
				<table class="table table-striped table-condensed table-hover">
					<tr><td><h4 class="text-center text-danger">业务监控标签配置</h4></td></tr>
					<tr><td>
					<input id="content" name="content" value="" type="hidden"/>
					<div id="editor" class="editor">${model.content}</div>
					</td></tr>
					<tr>
						<td  style="text-align:center"><input class='btn btn-primary' id="tagConfig"
							type="submit" name="submit" value="提交" /></td>
					</tr>
				</table>
			</form>
			<h4 class="text-center text-danger" id="state">&nbsp;</h4>
			
</a:config>
<script type="text/javascript">
	$(document).ready(function() {
		$('#application_config').addClass('active open');
		$('#businessTag').addClass('active');

		var state = '${model.opState}';
		if(state=='Success'){
			$('#state').html('操作成功');
		}else{
			$('#state').html('操作失败');
		}
		setInterval(function(){
			$('#state').html('&nbsp;');
		},3000);
	});
</script>